# Not 'language: python' because there will be projects in multiple languages.
language: minimal
dist: xenial

cache: pip
install:
- sudo add-apt-repository ppa:deadsnakes/ppa -y # python3.7 is unavailable in Xenial
- sudo apt-get update
- sudo apt-get install python3.7
- virtualenv --python=python3.7 .py37
- source .py37/bin/activate
- python --version
- pip install -r requirements.txt -r requirements-dev.txt
script:
- find task?? -iname '*.py' | xargs pycodestyle --show-source
- pytest task02
- pytest task03
- pytest task04
- pytest task06
